### ISSUE TITLE
Huawei P8 Lite bootloop with v79

### ISSUE THREAD

**Issue by oburtchen** [rovo89/android_art#30] opened 2016-01-31 15:26 UTC
Well, as the subject says. Logfile attached (wiped cache, rebooted and logged 'til first loop). Please let me know, if you need more information or I can do something more. Thanks a lot for your work.
[logcat.txt](https://github.com/rovo89/android_art/files/111320/logcat.txt)

**Comment by rovo89** [comment] 2016-02-01 09:10
Duplicate of https://github.com/rovo89/Xposed/issues/72 and https://github.com/rovo89/Xposed/issues/121

**Closed as completed by rovo89** 2016-02-01 09:10 UTC
Labels: duplicate
