### ISSUE TITLE
Crash on SVoice after enabling "everything" filter

### ISSUE THREAD

**Issue by wanam** [rovo89/android_art#19] opened 2015-11-22 12:56 UTC
After applying this commit https://github.com/rovo89/android_art/commit/23990d0013738354cdbe9f64209e0dbfda1a32ed it fixed a boot loop on stock Odex TW Roms running "everything" filter, but i'm getting a crash with SVoice App.

Here are the logs: http://pastebin.com/DgAFUBg6
Crashing App: https://www.dropbox.com/s/wvgvmcb2aidaxui/S-Voice_Android_phone.zip?dl=0

**Comment by rovo89** [comment] 2015-11-23 22:08
I can reproduce this with the ActivityManagerService constructor on Genymotion as soon as I compile the ROM with the "everything" filter. Do you have any ideas already why this happens?

**Comment by wanam** [comment] 2015-11-24 12:21
I assume the class initializers are not compiled unless we are on "everything" filter, but i have no idea why "invoke-virtual-quick" instruction is used there, neither how we can handle it.

**Comment by rovo89** [comment] 2015-11-25 08:49
After several hours of debugging, I think I understood what's going on here. In my case, there's a call from the constructor (not the class initializer!) of `ActivityManagerService` to `BatteryStatsService.getActiveStatistics()`: https://github.com/android/platform_frameworks_base/blob/android-5.1.1_r29/services/core/java/com/android/server/am/ActivityManagerService.java#L2087

In dex code, this is an invoke-virtual-quick, which says "call the method at index 95 of the vtable of the BatteryStatsService class" instead of "find method 9008 in the dex file, check how BatteryStatsService has overwritten it and then call it".

However, ART has "sharpened" this call because it found out that the target method has to be the one implemented in `BatteryStatsService`, e.g. because this class is final, so there can't be a subclass which would override the implementation and thus would require the vtable. As a consequence, it handles this call like one to a direct method (e.g. private/static) which doesn't need a vtable lookup. Instead, we're back to "find method 9008 in the dex file and call it".

This lookup in the dex file is cached (in a native `DexCache` object), which is initially filled with dummy "runtime" methods which have there entry points set to `art_quick_resolution_trampoline`. This method is supposed to do the lookup by analysing the statement that called it and will afterwards update the `DexCache` with the real method for entry 9008. The next time such a call is done, it will then go to the real method's entrypoint directly instead of the trampoline.

Unfortunately, the invoke-virtual-quick instruction isn't expected by the trampoline. One solution might be to add support for it in the trampoline. We can't derive the value "9008" from the instruction, but we should have the "this" reference and we have the vtable index, so should be able to determine the method and should get the dex method index from it in order to update the dex cache.

But maybe a better solution would be avoiding this call to the trampoline completely. It's not clear to my which sharpening is required anyway in such a case. It could be useful if the entrypoint of the method was known at compile time, but this has to be prevented for Xposed to work. The next best alternative would be a direct pointer to the method, which should be ok for Xposed. However, even AOSP allows this only for methods in the boot image, and Xposed currently prevents this it by forcing the use of the dex cache (92e8c8e0309c4a584f4279c478d54d8ce036ee59). Maybe there would be a little potential for optimization here, but I don't really think this helps us here.

So again, the question is whether the call even needs to be sharpened. Getting the relevant dex cache from the current method, then getting the method at the correct index and calling it seems to be equal effort as getting the class from the target object, getting the method at the vtable index and calling it.

**Comment by wanam** [comment] 2015-11-25 09:46
Great analysis!
When you say "equal effort", you mean development effort or execution time?

**Comment by rovo89** [comment] 2015-11-27 16:40
Execution time. Both variants already exist, for virtual vs. direct methods. Currently, the way for direct methods (via dex cache) is used, so it's a matter of disabling the sharpening for invoke-virtual-quick to use the way for virtual methods (via vtable). I'll try this now.

**Comment by rovo89** [comment] 2015-11-27 17:55
@wanam If you have the time, could you test this please? 181cb39f1b254b0a1605b204ad43112c5e6f5407

**Comment by wanam** [comment] 2015-11-27 19:06
@rovo89 I'm sorry I'm not at home for the next two days, i cannot test it now, i will test and report back Sunday.

**Comment by wanam** [comment] 2015-11-29 19:17
@rovo89 I tested you commit https://github.com/rovo89/android_art/commit/181cb39f1b254b0a1605b204ad43112c5e6f5407 and it seems to fix this issue.
Thank you.

**Comment by rovo89** [comment] 2015-12-17 21:18
This is fixed with v79. Note that I had to make a little change to this commit (move the "return" before the access check) and added other commits, so please check what you might need to merge.

**Closed as completed by rovo89** 2015-12-17 21:18 UTC
