### ISSUE TITLE
Randomly bootloop after manual restart Xperia Z5

### ISSUE THREAD

**Issue by solirf** [rovo89/android_art#39] opened 2016-05-08 15:24 UTC
Hi 
Here my log

https://drive.google.com/file/d/0B6qIFeOWWC5kMnZMZVV2YmlpNXc/view?usp=drivesdk

**Comment by rovo89** [comment] 2016-05-09 14:39
Why did you open another issue? Closed as duplicate of #36.

**Closed as completed by rovo89** 2016-05-09 14:39 UTC
Labels: duplicate
