### ISSUE TITLE
xposed not working on 5.1 Sony ROMs

### ISSUE THREAD

**Issue by pavansaragadam** [rovo89/android_art#17] opened 2015-10-13 19:22 UTC
Hello sir...my name is pavan.. I think yu remembered me...I had already posted the issue of xposed fr 5.0.2 Sony Xperia t2 ultra...then u said some files are corrupted in ur rom can't be fixed...
But
Nw recently we gt 5.1.1 update for our unfortunately nw also xposed not working 
Here I'm attaching the log file link
http://d-h.st/esmY
Thanks inadvance..hoping it will be fixed

**Comment by rovo89** [comment] 2015-10-14 13:05
It's still the same error in the logs, so it seems that even the new ROMs are broken. Closing it as a duplicate of #13 (and rovo89/Xposed#64) . If you manage to decompile/deodex /system/framework/arm/services.odex, please reopen that issue, but otherwise, I see no chance for Xposed to support those ROMs.

**Closed as completed by rovo89** 2015-10-14 13:05 UTC
Labels: duplicate, incompatibility
